### ISSUE TITLE
backup process fails with Onenote feedback installed

### ISSUE THREAD

**Issue by upats** [MSOpenTech/moodle-assignfeedback_onenote#1]
See discussion on the moodle forums here: https://moodle.org/mod/forum/discuss.php?d=311197#p1255602

When taking a backup while the onenote feedback plugin is installed, the following error occurs, causing the backups to fail:

Default exception handler: error/multiple_optigroup_duplicate_element Debug:
Error code: multiple_optigroup_duplicate_element
$a contents: feedback_file
* line 144 of /backup/util/structure/base_optigroup.class.php: base_optigroup_exception thrown
* line 108 of /backup/util/structure/base_nested_element.class.php: call to base_optigroup->add_used()
* line 173 of /backup/util/structure/base_nested_element.class.php: call to base_nested_element->check_and_set_used()
* line 48 of /mod/assign/feedback/onenote/backup/moodle2/backup_assignfeedback_onenote_subplugin.class.php: call to base_nested_element->add_child()
* line 60 of /backup/moodle2/backup_subplugin.class.php: call to backup_assignfeedback_onenote_subplugin->define_grade_subplugin_structure()
* line 137 of /backup/moodle2/backup_stepslib.php: call to backup_subplugin->define_subplugin_structure()
* line 139 of /mod/assign/backup/moodle2/backup_assign_stepslib.php: call to backup_activity_structure_step->add_subplugin_structure()
* line 88 of /backup/util/plan/backup_structure_step.class.php: call to backup_assign_activity_structure_step->define_structure()
* line 181 of /backup/util/plan/base_task.class.php: call to backup_structure_step->execute()
* line 214 of /backup/moodle2/backup_activity_task.class.php: call to base_task->execute()
* line 177 of /backup/util/plan/base_plan.class.php: call to backup_activity_task->execute()
* line 120 of /backup/util/plan/backup_plan.class.php: call to base_plan->execute()
* line 320 of /backup/controller/backup_controller.class.php: call to backup_plan->execute()
* line 100 of /home/deploy/moodle-autobr/backup.php: call to backup_controller->execute_plan()

**Comment by jamesmcq** [comment]
@upats The newest version of this plugin should resolve this issue - please update and let me know. Thanks for the report!
